exclude: 'wip|rough|errant'
repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      name: black-py
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
  -   id: pyupgrade
      name: pyupgrade-py

# Pylint does dynamic checks
- repo: local
  hooks:
  -   id: pylint
      name: pylint-py
      # Add project root path
      entry: pylint --init-hook="import sys,os; sys.path.append(os.getcwd())"
      args : [
        # black handles this except for string(C0301)
        # similar lines in multiple files(R0801)
        # attribute defined outside __init__(W0201)
        # capital constants rule(C0103)
        # too few public methods (R0903)
        # too many arguments (R0913)
        # catching too general exception(W0703)
        # fix-me (W0511)
        # too many branches (R0912)
        # Too general exception (W0719)
        "--disable=C0301,R0801,W0201,C0103,R0903,R0913,W0703,W0511,R0912,W0719",
        # Allow 2-30 char variables
        "--variable-rgx=[a-z_][a-z0-9_]{1,30}$",
        # Allow 2-30 char attributes,args
        "--attr-rgx=[a-zA-Z_][a-zA-Z0-9_]{1,30}$",
        "--argument-rgx=[a-z_][a-z0-9_]{1,30}$",
        #  Exclude module member access for E1101
        "--generated-members=torch.*,pandas.*,Levenshtein.*",
        # Max local variables
        "--max-locals=25",
        # Exclusion for source unavailable pkgs
        "--extension-pkg-whitelist=lxml",
        # Max Attributes for a class
        "--max-attributes=20",
        # Ignore folder
        "--ignore=scripts/errant/",
      ]
      language: system
      files : \.py$
      require_serial: true