[tool.poetry]
name = "bhaasha"
version = "0.1.0"
description = ""
authors = ["Praful932 <praful.mohanan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.0.0-cp38-none-macosx_11_0_arm64.whl"}
transformers = "^4.27.4"
evaluate = "^0.4.0"
datasets = "^2.11.0"
pandas = "^2.0.0"
numpy = "^1.24.2"
tqdm = "^4.65.0"
scikit-learn = "^1.3"
accelerate = "^0.18.0"
jupyter = "^1.0.0"
jupyter-contrib-nbextensions = "^0.7.0"
jedi = "0.17.2"
sentencepiece = "^0.1.97"
pre-commit = "^3.2.2"
pylint = "^2.17.2"
toma = "^1.1.0"
nvidia-ml-py3 = "^7.352.0"
langchain = "^0.0.189"
protobuf = "^4.23.3"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
py7zr = "^0.20.4"
nltk = "^3.8.1"
rouge-score = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
